<!DOCTYPE html>
<html lang="nl">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Clip</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?php echo $this->stylesheet_relative_directory; ?>">
</head>
<body>
    <div class="center-container">
        <div class="clip_background">
            <h1>Clip  </h1>
            <div class="clip">
                <div class="wrap">
                    <div class="clip_information">
                        <div class="clip-pic wthree">
                            <img src="https://img.youtube.com/vi/<?php if ( array_key_exists( 'id', $this->parameters ) ) { echo $this->parameters[ 'id' ]; }?>/hqdefault.jpg" alt="Clip image">
                            <h3><?php if ( array_key_exists( 'title', $this->parameters ) ) { echo $this->parameters[ 'title' ]; }?></h3>
                            <div class="w3ls-agile-left">
                                <ul class="clip-details">
                                    <li>
                                        <ul class="clip-details-text">
                                            <li><b>Doel </b></li>
                                            <li>: </li>
                                            <li> <span class="w3"><?php if ( array_key_exists( 'goal', $this->parameters ) ) { echo $this->parameters[ 'goal' ]; }?></span></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <ul class="clip-details-text">
                                            <li><b>Gebruik </b></li>
                                            <li>: </li>
                                            <li> <span class="w3"><?php if ( array_key_exists( 'usage', $this->parameters ) ) { echo $this->parameters[ 'usage' ]; }?></span></li>
                                        </ul>
                                    </li>
                                </ul>
                                <div class="clear"></div>
                            </div>
                        </div>

                        <div class="clip-ser">
                            <h4>Statistieken</h4>
                            <div class="awards-agileinfo  w3ls-section">
                                <div class="awardsw3-agileits banner-agileinfo">
                                    <div class="container">
                                        <div class="w3ls_banner_bottom_grids">
                                            <div class="statistics_container">
                                                <div class="clip_statistic">
                                                    <div class="circlechart" data-percent="<?php
                                                            if ( array_key_exists( 'duration', $this->parameters ) )
                                                            {
                                                                sscanf( $this->parameters[ 'duration' ], '%d:%d:%d', $hours, $minutes, $seconds );
                                                                if ( isset( $seconds ) )
                                                                {
                                                                    $time_in_seconds = $hours * 3600 + $minutes * 60 + $seconds;
                                                                }
                                                                else if ( isset( $minutes ) )
                                                                {
                                                                    $time_in_seconds = $hours * 60 + $minutes;
                                                                }
                                                                else
                                                                {
                                                                    $time_in_seconds = $hours;
                                                                }
                                                                echo max ( 0, 100 - round ( $time_in_seconds / 9 ) );
                                                            }?>" data-text="<?php if ( array_key_exists( 'duration', $this->parameters ) ) { echo $this->parameters[ 'duration' ]; }?>"></div>
                                                    <h4>Tijd</h4>
                                                </div>
                                            </div>
                                            <div class="statistics_container">
                                                <div class="clip_statistic">
                                                    <div class="circlechart" data-percent="<?php if ( array_key_exists( 'advice', $this->parameters ) ) { echo $this->parameters[ 'advice' ]; }?>" data-text="<?php if ( array_key_exists( 'advice', $this->parameters ) ) { echo $this->parameters[ 'advice' ]; }?>%"></div>
                                                    <h4>Advies</h4>
                                                </div>
                                            </div>
                                            <div class="statistics_container">
                                                <div class="clip_statistic">
                                                    <div class="circlechart" data-percent="<?php if ( array_key_exists( 'views', $this->parameters ) ) { echo round( log( $this->parameters[ 'views' ] ) ); }?>" data-text="<?php if ( array_key_exists( 'views', $this->parameters ) ) { echo $this->parameters[ 'views' ]; }?>"></div>
                                                    <h4>Weergaven</h4>
                                                </div>
                                            </div>
                                            <div class="clear"> </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://www.hedude.com/scripts/circlechart.js"></script>
    <script>$('.circlechart').percentcircle();</script>
</body>
</html>
